# Generated by Django 4.1.7 on 2026-02-13 15:14

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('_id', models.CharField(default=api.models.generate_object_id, max_length=24, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=24)),
                ('activity_type', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('distance', models.FloatField(blank=True, null=True)),
                ('calories', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activities',
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('_id', models.CharField(default=api.models.generate_object_id, max_length=24, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=24)),
                ('team_id', models.CharField(max_length=24)),
                ('total_points', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'leaderboard',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('_id', models.CharField(default=api.models.generate_object_id, max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', models.CharField(default=api.models.generate_object_id, max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('team_id', models.CharField(blank=True, max_length=24, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('_id', models.CharField(default=api.models.generate_object_id, max_length=24, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('exercise_type', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('calories_estimate', models.IntegerField()),
            ],
            options={
                'db_table': 'workouts',
            },
        ),
    ]
